  version: '3.8'
  services:
    postgres:
      image: postgres
      environment:
        POSTGRES_USER: neondb_owner 
        POSTGRES_DB: neondb 
        POSTGRES_PASSWORD: npg_e7GAVmRNtEw0 
      ports:
        - "5432:5432" 
      networks:
        - sudo-flix-network
    sudo-flix:
      image: ghcr.io/sussy-code/backend:latest
      environment:
        MWB_POSTGRES__CONNECTION: postgresql://neondb_owner:npg_e7GAVmRNtEw0@ep-green-cell-a8jmxvzu-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
        MWB_CRYPTO__SESSION_SECRET: Wf-BWFuf@xnURDNu!qVVGEK*9zHu4bnX 
        MWB_META__NAME: unofficial-sudo-flix 
        MWB_POSTGRES__MIGRATE_ON_BOOT: "true"
        MIKRO_ORM_MIGRATIONS_DISABLE_FOREIGN_KEYS: "true" 
      ports:
        - "80:80"
      depends_on:
        - postgres
      networks:
        - sudo-flix-network
  networks:
    sudo-flix-network: 
      driver: bridge
